# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [main, testBranch]
  pull_request:
    branches: [main, development]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 16.19.0
          cache: "npm"
      - name: Install and test
        run: |
          export API_KEY=${API_KEY}
          npm ci
          npm run build --if-present
          npm run testJest
        env:
          API_KEY: ${{ secrets.API_KEY }}
