name: Node.js CI

on:
  push:
    branches: [ testBranch ]
  pull_request:
    branches: [ main ]

jobs:
  jobs:
  unit-test:
    name: unit-test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Unit Tests
      run: |
        npm install
        npm install -g jest
        npm run testJest